version: '2'

services:
    nginx:
        depends_on:
          - wordpress
        image: nginx:1.10.3-alpine
        ports:
            - 80:80
            - 443:443
        volumes_from:
          - wordpress
        volumes:
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - wp-network
    wordpress:
        depends_on:
          - db
        image: wordpress:4.7.3-php7.1-fpm-alpine
        volumes:
            - ./htdocs:/var/www/html
            - ./plugins:/var/www/html/wp-content/plugins
            - ./themes:/var/www/html/wp-content/themes
        environment:
          WORDPRESS_DB_HOST: db:3306
          WORDPRESS_DB_PASSWORD: root
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_NAME: wordpress
          WORDPRESS_TABLE_PREFIX: wp_
          WORDPRESS_DEBUG: 1
        networks:
            - wp-network
    db:
      image: mysql:5.7
      restart: always
      volumes:
        - db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
      networks:
        - wp-network
    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
      networks:
        - wp-network
networks:
    wp-network:
        driver: bridge
volumes:
  db_data:
